### ISSUE TITLE
Tests included in hard-gym change as Leetcode adds problems

### ISSUE THREAD

**Issue by liamsaliba** [GammaTauAI/leetcode-hard-gym#15]
Hi,

Firstly, nice work with your project.

I notice that in `fetch_dataset`, the method of obtaining the dataset for leetcode-hard-gym is as follows:
```python
    hard = [q for q in question_infos.stat_status_pairs
            if q.difficulty.level == 3
            and q.paid_only == False]

    uncontaminated = hard[:41] # First question after 41 is contaminated

...
```

I assume (but not sure if) elements in `hard` are ordered from newest to oldest problem, but in any case, this code selects the newest 41 (not 40) problems, and will select different problems to those used in the Reflexion paper as long as Leetcode adds new Hard problems.

I checked my generated `leetcode-hard-uncontaminated-python3.jsonl`, and I don't have the task `paths-in-matrix-whose-sum-is-divisible-by-k`, while it is present in [the one used in Reflexion](https://github.com/GammaTauAI/leetcode-hard-gym/blob/98093a26c87d0cc88a46a766e50a5354c4b7733d/leetcode_dataset/data/humaneval/leetcode-hard-py-40-uncontaminated.jsonl).

I think that the method used to obtain the problems should ensure the problems generated are consistent to ensure fair comparison between models using this benchmark.

**Comment by cassanof** [comment]
@becklabs is the main author of the project. But I will give my two thoughts here before he may respond.


In general, this is a problem we cannot fix with the current solution. The hidden tests on LeetCode are not available to us, and thus they may change at any time. I have been working on an offline version of the benchmark, incorporating it into the [MultiPL-E framework for multi-lingual evaluation](https://github.com/nuprl/MultiPL-E). See the PR here: https://github.com/nuprl/MultiPL-E/pull/98

**Comment by becklabs** [comment]
@liamsaliba Yes, this was identified as an issue and was fixed last week. Uncontaminated problems are now defined as the 39 problems after the problem with the slug paths-in-matrix-whose-sum-is-divisible-by-k. Please pull origin to see the changes reflected. Thanks.
