### ISSUE TITLE
Leetcode API error

### ISSUE THREAD

**Issue by shenao-zhang** [GammaTauAI/leetcode-hard-gym#18]
Hi,

I encountered the following API error, have you encountered this and any suggestions on how to fix it?

> leetcode.rest.ApiException: (403)
> Reason: Forbidden
> HTTP response headers: HTTPHeaderDict({'Date': 'Fri, 17 Nov 2023 01:02:00 GMT', 'Content-Type': 'application/json', 'Content-Length': '38', 'Connection': 'keep-alive', 'x-frame-options': 'DENY', 'vary': 'Cookie', 'set-cookie': 'LEETCODE_SESSION=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.e30.KpufdHIo8CeGduwC5DCQoba8bmWCjJ9mUTYQ4npFdlk; Domain=.leetcode.com; expires=Fri, 01 Dec 2023 01:02:00 GMT; HttpOnly; Max-Age=1209600; Path=/; SameSite=Lax; Secure', 'strict-transport-security': 'max-age=31536000; includeSubDomains; preload', 'CF-Cache-Status': 'DYNAMIC', 'Report-To': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=LUFCrzz1caB5AX8GXL6VjegtnkfzT1smWIr%2Fzt3ZS%2FusJeoKOQCit7MEq4T2PaQLWnCOCH0H8OiHdKG0fJ%2FVLSxqCVhdaIfm6aaCIgfjz%2BevgOd7QjdR6%2BRbXjBGyQ%3D%3D"}],"group":"cf-nel","max_age":604800}', 'NEL': '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}', 'X-Content-Type-Options': 'nosniff', 'Server': 'cloudflare', 'CF-RAY': '82740bb30d1c62a5-ORD'})
> HTTP response body: {"error": "User is not authenticated"}

Best,
Shenao

**Comment by mkj69** [comment]
I'm experiencing the same problem, may I ask how you solved it?
